from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
ANNOTATIONS_DIR = DATA_DIR / "annotations"

DOCS_DIR = PROJECT_ROOT / "docs"

RESULTS_DIR = PROJECT_ROOT / "results"
ANNOTATION_QUALITY_DIR = RESULTS_DIR / "annotation_quality"
MODEL_RUNS_DIR = RESULTS_DIR / "model_runs"
CONTEXT_EXPERIMENTS_DIR = RESULTS_DIR / "context_experiments"
ROUND3_REAUDIT_DIR = RESULTS_DIR / "round3_reaudit"
VALIDATION_DIR = RESULTS_DIR / "validation"

SOURCE_WORKBOOK = RAW_DATA_DIR / "source_workbook_token404_sample_yh.xlsx"

SENTENCES_CANONICAL = PROCESSED_DATA_DIR / "sentences_canonical.csv"
DOC_SPLITS_FIXED = PROCESSED_DATA_DIR / "doc_splits_fixed.csv"
PILOT_DATASET_SUMMARY = PROCESSED_DATA_DIR / "pilot_dataset_summary.json"

SEED_ANNOTATIONS_ROUND1 = ANNOTATIONS_DIR / "seed_annotations_round1.csv"
BOUNDARY_RELABEL_QUEUE_ROUND1 = ANNOTATIONS_DIR / "boundary_relabel_queue_round1.csv"
MASTER_ANNOTATIONS_WORKING = ANNOTATIONS_DIR / "master_annotations_working.csv"
ROUND2_STAGE_A_ANNOTATIONS = ANNOTATIONS_DIR / "round2_stage_a_annotations.csv"
ROUND2_STAGE_A_BLIND_REVIEW = ANNOTATIONS_DIR / "round2_stage_a_blind_review.csv"
ROUND2_STAGE_B_ANNOTATIONS = ANNOTATIONS_DIR / "round2_stage_b_annotations.csv"
ROUND2_ADJUDICATED_ANNOTATIONS = ANNOTATIONS_DIR / "round2_adjudicated_annotations.csv"
MASTER_ANNOTATIONS_FULL_ROUND3 = ANNOTATIONS_DIR / "master_annotations_full_round3.csv"

ANNOTATION_GUIDELINES_ROUND1 = DOCS_DIR / "annotation_guidelines_round1.md"
ANNOTATION_GUIDELINES_ROUND2 = DOCS_DIR / "annotation_guidelines_round2.md"
ANNOTATION_PROCESS_DOC = DOCS_DIR / "annotation_process.md"
PROJECT_STRUCTURE_DOC = DOCS_DIR / "project_structure.md"

ROUND1_BOUNDARY_REVIEW_DIR = ANNOTATION_QUALITY_DIR / "round1_boundary_review"
ROUND2_ADJUDICATION_DIR = ANNOTATION_QUALITY_DIR / "round2_adjudication"
ROUND1_BOUNDARY_DISAGREEMENTS = ROUND1_BOUNDARY_REVIEW_DIR / "boundary_disagreements.csv"
ROUND1_BOUNDARY_DISAGREEMENT_SUMMARY = ROUND1_BOUNDARY_REVIEW_DIR / "boundary_disagreement_summary.json"
ROUND2_DOUBLE_CHECK_COMPARISON = ROUND2_ADJUDICATION_DIR / "stage_a_double_check_comparison.csv"
ROUND2_ANNOTATION_SUMMARY = ROUND2_ADJUDICATION_DIR / "round2_annotation_summary.json"

PROXY_SMOKE_RUN_DIR = MODEL_RUNS_DIR / "proxy_smoke_legacy_proxy"
PILOT_ROUND1_RUN_DIR = MODEL_RUNS_DIR / "pilot_round1_seed"
PILOT_ROUND2_RUN_DIR = MODEL_RUNS_DIR / "pilot_round2_master"
PROXY_SMOKE_WINNER_PREDICTIONS = PROXY_SMOKE_RUN_DIR / "winner_predictions.csv"
PROXY_SMOKE_WINNER_EMBEDDINGS = PROXY_SMOKE_RUN_DIR / "winner_embeddings.npy"
PILOT_ROUND1_ACTIVE_LEARNING_BATCH = PILOT_ROUND1_RUN_DIR / "active_learning_batch_round1.csv"
PILOT_ROUND1_WINNER_PREDICTIONS = PILOT_ROUND1_RUN_DIR / "winner_predictions.csv"
PILOT_ROUND1_WINNER_EMBEDDINGS = PILOT_ROUND1_RUN_DIR / "winner_embeddings.npy"
PILOT_ROUND2_ACTIVE_LEARNING_BATCH = PILOT_ROUND2_RUN_DIR / "active_learning_batch_round2.csv"
PILOT_ROUND2_WINNER_PREDICTIONS = PILOT_ROUND2_RUN_DIR / "winner_predictions.csv"
PILOT_ROUND2_WINNER_EMBEDDINGS = PILOT_ROUND2_RUN_DIR / "winner_embeddings.npy"

CONTEXT_EXPERIMENT_ROUND1_DIR = CONTEXT_EXPERIMENTS_DIR / "working_master_round1"
CONTEXT_EXPERIMENT_ROUND2_DIR = CONTEXT_EXPERIMENTS_DIR / "working_master_round2"
CONTEXT_EXPERIMENT_ROUND1_COMPARISON = CONTEXT_EXPERIMENT_ROUND1_DIR / "context_comparison.json"
CONTEXT_EXPERIMENT_ROUND2_COMPARISON = CONTEXT_EXPERIMENT_ROUND2_DIR / "context_comparison.json"

ROUND3_ISSUE_REAUDIT_DIR = ROUND3_REAUDIT_DIR / "issue"
ROUND3_REMEDIATION_REAUDIT_DIR = ROUND3_REAUDIT_DIR / "remediation"
ROUND3_OTHER_REAUDIT_DIR = ROUND3_REAUDIT_DIR / "other"
ROUND3_ISSUE_BATCH_MANIFEST = ROUND3_ISSUE_REAUDIT_DIR / "manifests" / "batch_manifest.csv"
ROUND3_ISSUE_BATCH_SUMMARY = ROUND3_ISSUE_REAUDIT_DIR / "manifests" / "batch_summary.csv"
ROUND3_ISSUE_MERGED = ROUND3_ISSUE_REAUDIT_DIR / "merged_annotations.csv"
ROUND3_ISSUE_OVERLAY = ROUND3_ISSUE_REAUDIT_DIR / "overlay_annotations.csv"
ROUND3_ISSUE_SUMMARY_JSON = ROUND3_ISSUE_REAUDIT_DIR / "summary.json"
ROUND3_ISSUE_SUMMARY_CSV = ROUND3_ISSUE_REAUDIT_DIR / "summary.csv"

ROUND3_REMEDIATION_BATCH_MANIFEST = ROUND3_REMEDIATION_REAUDIT_DIR / "manifests" / "batch_manifest.csv"
ROUND3_REMEDIATION_BATCH_SUMMARY = ROUND3_REMEDIATION_REAUDIT_DIR / "manifests" / "batch_summary.csv"
ROUND3_REMEDIATION_MERGED = ROUND3_REMEDIATION_REAUDIT_DIR / "merged_annotations.csv"
ROUND3_REMEDIATION_OVERLAY = ROUND3_REMEDIATION_REAUDIT_DIR / "overlay_annotations.csv"
ROUND3_REMEDIATION_SUMMARY_JSON = ROUND3_REMEDIATION_REAUDIT_DIR / "summary.json"
ROUND3_REMEDIATION_SUMMARY_CSV = ROUND3_REMEDIATION_REAUDIT_DIR / "summary.csv"
ROUND3_REMEDIATION_MASTER_OVERLAP = ROUND3_REMEDIATION_REAUDIT_DIR / "master_overlap_comparison.csv"

ROUND3_OTHER_BATCH_MANIFEST = ROUND3_OTHER_REAUDIT_DIR / "manifests" / "batch_manifest.csv"
ROUND3_OTHER_BATCH_SUMMARY = ROUND3_OTHER_REAUDIT_DIR / "manifests" / "batch_summary.csv"
ROUND3_OTHER_MERGED = ROUND3_OTHER_REAUDIT_DIR / "merged_annotations.csv"
ROUND3_OTHER_OVERLAY = ROUND3_OTHER_REAUDIT_DIR / "overlay_annotations.csv"
ROUND3_OTHER_SUMMARY_JSON = ROUND3_OTHER_REAUDIT_DIR / "summary.json"
ROUND3_OTHER_SUMMARY_CSV = ROUND3_OTHER_REAUDIT_DIR / "summary.csv"

VALIDATION_RANDOM_SAMPLE_NOTE = VALIDATION_DIR / "random_sample_reaudit_validation_2026-04-19.md"
